services: 
 mariadb:
  container_name: web-mariadb-15
  hostname: mariadb
  image: mariadb:10.5
  restart: always
  environment:
   MARIADB_ROOT_PASSWORD: password
   MARIADB_DATABASE: 15_Calculator
   MARIADB_USER: root
   MARIADB_PASSWORD: password
  ports:
   - "0.0.0.0:5115:3306"
 
 web:
  container_name: 15_Calculator
  hostname: app
  build: .
  ports:
   - "0.0.0.0:5015:5015"