version: "3.9"

services:
  web:
    container_name: 15_calculator-web
    hostname: app
    build: .
    ports:
      - "5015:5015"
    networks:
      - metrics-net

  prometheus:
    image: prom/prometheus:latest
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9105:9090"
    depends_on:
      - web
    networks:
      - metrics-net

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "5055:8081"
    networks:
      - metrics-net

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
      - renderer
    ports:
      - "3015:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:5055/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3015/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - metrics-net

networks:
  metrics-net:
    name: metrics-net
